[tool.poetry]
name = "unpact"
version = "0.0.12"
description = "A lightweight library for tabulating dictionaries"
authors = ["Moph Toyer <chris@telemetry.fm>"]
license = "MIT"
readme = "README.md"
keywords = ["tables", "formatting", "flat", "flattening", "json"]
packages = [{include = "unpact"}]

[tool.poetry.dependencies]
python = "^3.9 || ^3.10 || ^3.11"
typing-extensions = "^4.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
mypy = "^1.5.0"
poethepoet = "^0.22.0"
polars = "^0.18.14"
orjson = "^3.9.5"
msgspec = "^0.18.1"
ipykernel = "^6.25.1"
tox = "^4.9.0"
pytest-cov = "^4.1.0"
coverage-badge = "^1.1.0"

[tool.poe.tasks]
lint = "mypy unpact"
format = "black ."
check = "black . --check"
test = "pytest"
precommit = "tox run"
coverage_test = 'coverage run -m pytest tests'
coverage_report = 'coverage report'
coverage = "pytest --cov=unpact --cov-report term-missing"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
