[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gdbus-util"
version = "0.0.2"
authors = [
  { name="Adrian Dombeck", email="adrian.dombeck@gmail.com" },
]
description = "Easy GDBus service creation with exit-on-idle functionality"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Documentation = "https://python-gdbus-util.readthedocs.io/en/latest/"
GitHub = "https://github.com/adombeck/python-gdbus-util"
Issues = "https://github.com/adombeck/python-gdbus-util/issues"
