[tool.poetry]
name = "squiz"
version = "0.2.1"
description = "View a Python object's direct and nested members."
authors = ["morefigs"]
readme = "README.md"
homepage = "https://github.com/morefigs/squiz/"

[tool.poetry.dependencies]
python = "^3.10"
colorama = "^0.4.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
