[tool.poetry]
name = "vinyl-core"
version = "0.0.3"
description = "A python framework for building next-gen analytics infrastructure"
authors = [
    "Ian Tracey <ian@turntable.so>",
    "Justin Leder <justin@turntable.so>"
]
license = "LICENSE.md"
readme = "README.md"
packages = [{ include = "vinyl" }]


[tool.poetry.dependencies]
python = ">=3.10, <4.0"
typer = { extras = ["all"], version = "^0.9.0" }
boto3 = "^1.34.13"
rustworkx = "^0.13.2"
pydantic = "^2.5.3"
python-dotenv = "^1.0.0"
sqlglot = { extras = ["rs"], version = "^20.7.1" }
toml = "^0.10.2"
geopandas = "^0.14.2"
lets-plot = "^4.2.0"
watchdog = {extras = ["watchmedo"], version = "^3.0.0"}
fsspec = {version = "^2024.2.0"}
tqdm = "^4.66.1"
textual = "^0.49.0"
netext = "^0.2.1"
google-auth = "^2.28.0"
turntable-spoonbill = {version = "^8.0.0", extras = ["bigquery", "duckdb", "postgres", "snowflake"]}


[tool.poetry.scripts]
vinyl = 'vinyl.cli.main:app'

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ipython = "^8"
pyinstrument = "^4.6.1"
graphviz = "^0.20.1"
types-pytz = "^2023.3.1.1"
types-toml = "^0.10.8.7"
ipykernel = "^6.28.0"
vulture = "^2.10"
ipdb = "^0.13.13"
pandas-stubs = "^2.1.4.231227"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"

[tool.vinyl]
tz = "America/New_York"
dark-mode = true
module_name = "internal_project"

[tool.pytest.ini_options]
addopts = "--color=yes"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
