[tool.poetry]
name = "kitoboy-optimizator"
version = "0.1.73"
description = ""
authors = ["fdoooch <fdoooch@gmail.com>"]
readme = "README.md"

exclude = [
    "tests/",
    "kitoboy_optimizator/strategies/",
    "tests/data/",
    "tests/results/"
]


[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.3"
numba = "^0.59.0"
aiohttp = "^3.9.3"
pybit = "^5.6.2"
python-binance = "^1.0.19"
pandas = "^2.2.0"


[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pypi = "^2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
    