[tool.poetry]
name = "ascenderai"
version = "0.1.2"
description = "Python SDK library for interacting with AscenderAI clusters"
authors = ["AscenderTeam <info@ascender.space>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "3.9.3"
rich = "^13.7.0"
langchain = "^0.1.7"
langchain-community = "^0.0.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
