[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["app/application"]

[project]
name = "cli-jarvis"
version = "0.0.1"
authors = [
  { name="Aarsh Shah", email="aarsh@live.ca" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/AarshShah9/Jarvis-CLI"
Issues = "https://github.com/AarshShah9/Jarvis-CLI/issues"