[tool.poetry]
name = "otherworlds"
version = "1.2.0"
description = "A name generator for nonsensitive things"
authors = ["Jurnell Cockhren <jurnell@civichacker.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
packages = [
    { include = "otherworlds" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
reuse = "^1.1.2"
flake8 = { version = "^6.0.0", python = ">=3.8.1" }
vulture = "^2.7"
pytest = "^7.3.1"
tox = "^4.5.2"
pytest-cov = "^4.1.0"
mypy = "^1.7.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
otherworlds = 'otherworlds.console:run'

[tool.vulture]
ignore_names = ["run"]
paths = ["otherworlds"]
min_confidence = 80
sort_by_size = true
