[project]
name = "heerlijke-tools"
version = "0.4.0"
description = "Toolbox of development utilities for my personal use."
license = {file = "docs/license.md"}
authors = [
    { name = "Thomas Vanhelden", email = "thomas.vanhelden@gmail.com" }
]
dependencies = [
    "protoletariat>=3.2.19",
    "grpcio-tools>=1.60.1",
    "click>=8.1.7",
]
readme = "README.md"
requires-python = ">= 3.12"

[project.scripts]
heerlijke-tools = "heerlijke_tools:cli"

[project.urls]
Documentation = "https://cringelord-heerlijkeheer-806eb581859167e3efa6c9df4ab5e4bf17987f.gitlab.io/"
Repository = "https://gitlab.com/HeerlijkeHeer/HeerlijkeTools"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "bump-my-version>=0.17.4",
    "mkdocs-git-revision-date-localized-plugin>=1.2.4",
    "mkdocs-git-authors-plugin>=0.7.2",
    "mkdocs-material>=9.5.10",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/heerlijke_tools"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.sdist]
src-dir = "src"

[tool.bumpversion]
current_version = "0.4.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = true
tag_name = "{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = "--gpg-sign"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
