[tool.poetry]
name = "komoutils"
version = "0.0.204"
description = ""
authors = ["Makhosonke Morafo <makhosonke@komokun.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pendulum = "^3.0.0"
pymongo = "^4.6.2"
pytest = "^8.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
