[tool.poetry]
name = "antakia-ac"
version = "0.2.5"
description = ""
authors = ["Pierre Hulot <pierre@ai-vidence.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.12"
numba = "^0.59.0"
scipy = "^1.12.0"
scikit-learn = "^1.4.0"
tomaster = "^0.0.5"
#antakia-core = {path = "../antakia-core", develop = true}
antakia-core = "*"

[tool.poetry.group.dev.dependencies]
pyarmor = "^8.4.7"
pyarmor-webui = "^2.2"
pre-commit = "^3.5.0"
mkdocs = "^1.5.3"
mock = "^5.1.0"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

