[project]
name = "parcelfile"
version = "1.1.0"
authors = [
  { name="@malachi196", email="malachiaaronwilson@gmail.com" },
]
description = "Parcel does file command manipulation within python projects"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/malachi196/Parcelfile"
[tool.poetry]
name = "parcelfile"
version = "1.0.7"
description = "Parcel does file command manipulation within python projects"
authors = ["malachi196"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
setuptools = "^69.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
