[tool.poetry]
authors = ["Daniel CAUNE <daniel.caune@gmail.com>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
description = "Perseus Agent Python Library"
include = [
    "CHANGELOG.md"
]
keywords = ["core", "library", "perseus"]
license = "SEE LICENSE IN <LICENSE.md>"
name = "perseus-agent-library"
packages = [{ include = "majormode", from = "src" }]
readme = "README.md"
repository = "https://github.com/majormode/perseus-agent-python-library"
version = "1.0.10"

[tool.poetry.dependencies]
perseus-core-library = "^1.19"
perseus-getenv-library = "^1.0"
perseus-microrm-library = "^1.3"
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
