[tool.poetry]
name = "atro-args"
version = "0.6.20"
description = ""
authors = ["atropos <sv7n@pm.me>"]
readme = "README.md"
packages = [{ include = "atro_args" }]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.3.0"
python-dotenv = "^1.0.0"
pyyaml = "^6.0.1"
types-pyyaml = "^6.0.12.11"
atro-utils = "^0.0.8"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
pytest-mock = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 200
target-version = ['py311']
