[tool.poetry]
name = "pydantic-cli-model"
version = "0.1.0"
description = ""
authors = ["Matthew Billman <mgbvox@gmail.com>"]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/mgbvox/pydantic-cli-model"
Issues = "https://github.com/mgbvox/pydantic-cli-model/issues"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.6.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.1"
black = "^24.2.0"
ruff = "^0.2.2"
mypy = "^1.8.0"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-include-markdown-plugin = "^6.0.4"
mkdocstrings = {extras = ["python"], version = "^0.24.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
