[tool.poetry]
name = "jnb"
version = "1.0.0"
description = "Manage and Create Jupyter Notebooks"
authors = ["Udesh <devparzival404@gmail.com>"]
license = "MIT"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
nbformat = "^5.2.0"

[tool.poetry.dev-dependencies]
twine = "^5.0.0"
pytest = "^7.1.1"
tox = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
