[tool.poetry]
name = "pyspark-connectby"
version = "1.0.5"
description = "connectby hierarchy query in spark"
authors = ["Chen, Yu <cheny@fcc.ca>"]
readme = "README.md"
packages = [{include = "pyspark_connectby"}]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pyspark = ">3"

[tool.poetry.group.test.dependencies]
pytest = "^7"
pyspark = ">3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
